services:
  app1:
    image: 1234a4321/app3:1.2
    working_dir: /app
    volumes:
      - ./docker-compose.yml:/app/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_DB=0
    privileged: true
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge